export const ClientDetails = [
    {
      id: 1,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 2,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 3,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 4,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 5,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 6,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 7,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 8,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 9,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 10,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 11,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 12,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 13,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 14,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 15,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 16,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 17,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 18,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 19,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
];

export const filterData = 
[
  {id:1, filterName: "Request type", optionData: [
    {id:1, name: "Apartment", value: "apartment"},
    {id:2, name: "Villa", value: "villa"},
    {id:3, name: "Twinhouse", value: "twinhouse"},
    {id:4, name: "Townhouse", value: "townhouse"},
    {id:5, name: "Duplex", value: "duplex"},
  ]},
  {id: 2, filterName: "Leads Status", optionData: [
    { value: "قفل خارج الشركه", name: "قفل خارج الشركه" },
    { value: "قفل داخل الشركه", name: "قفل داخل الشركه" },
    { value: "مؤجل حاليا", name: "مؤجل حاليا" },
    { value: "لا يرد", name: "لا يرد" },
    { value: "not interested", name: "not interested" },
    { value: "very interested", name: "very interested" },
    { value: "متابع معاينات", name: "متابع معاينات" },
    { value: "interested", name: "interested" },
  ]},
  {id:3, filterName: "Leads Source", optionData: [
    {id:1, name: "facebook", value: "facebook"},
    {id:2, name: "whatsapp", value: "whatsapp"},
    {id:3, name: "youtupe", value: "youtupe"},
  ]},
  {id:4, filterName: "Leads Assign to", optionData: [
    {id:1, name: "Apartment", value: "apartment"},
    {id:2, name: "Villa", value: "villa"},
    {id:3, name: "Twinhouse", value: "twinhouse"},
    {id:4, name: "Townhouse", value: "townhouse"},
    {id:5, name: "Duplex", value: "duplex"},
  ]},
]