export const ClientDetails = [
    {
      id: 1,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 2,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 3,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 4,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 5,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 6,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 7,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 8,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 9,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 10,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 11,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 12,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 13,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 14,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 15,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 16,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 17,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 18,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 19,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
  ];