export const ClientDetails = [
    {
      id: 1,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 2,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 3,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 4,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 5,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 6,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 7,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 8,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 9,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 10,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 11,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 12,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 13,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 14,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 15,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 16,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 17,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 18,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
    {
      id: 19,
      name: "Ahmed",
      phone: "1 (123) 456-7890",
      source: "Ahmed",
      email: "Raymond@simmmple.com",
      DESC: "any",
    },
  ];


  export const filterData = [
    {id:1, filterName: "Property Types", optionData: [
      {id:1, name: "Apartment", value: "apartment"},
      {id:2, name: "Villa", value: "villa"},
      {id:3, name: "Twinhouse", value: "twinhouse"},
      {id:4, name: "Townhouse", value: "townhouse"},
      {id:5, name: "Duplex", value: "duplex"},
    ]},
    {id:1, filterName: "Bedrooms", optionData: [
      {id:1, name: "1 Bedrooms", value: "1 Bedrooms"},
      {id:2, name: "2 Bedrooms", value: "2 Bedrooms"},
      {id:3, name: "3 Bedrooms", value: "3 Bedrooms"},
      {id:4, name: "4 Bedrooms", value: "4 Bedrooms"},
      {id:5, name: "5+ Bedrooms", value: "5+ Bedrooms"},
    ]},
    {id:1, filterName: "Price", optionData: [
      {id:1, name: "1M To 4M", value: "1M To 4M"},
      {id:2, name: "4M To 10M", value: "4M To 10M"},
      {id:3, name: "10M To 15M", value: "10M To 15M"},
      {id:4, name: "15M To 30M", value: "15M To 30M"},
      {id:5, name: "30M To 50M", value: "30M To 50M"},
    ]},
    {id:1, filterName: "Property Types", optionData: [
      {id:1, name: "Apartment", value: "apartment"},
      {id:2, name: "Villa", value: "villa"},
      {id:3, name: "Twinhouse", value: "twinhouse"},
      {id:4, name: "Townhouse", value: "townhouse"},
      {id:5, name: "Duplex", value: "duplex"},
    ]},
  ]