'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import Menu from "../src/components/menu/page";
import { usePathname } from 'next/navigation';
import { Box } from "@mui/material";
import "../public/assets/sass/shares.css"
import "./globals.css"
import Setting from "../src/components/setting-drawer/page"
const geistSans = localFont({

  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Check if the current path is the homepage ("/")
  const isHomePage = pathname === "/";

  return (
    <html>
      <body>
      
        {!isHomePage && <Menu children={children} />}
        {/* Conditionally render Menu only if not on the homepage */}
        {
          isHomePage && <Box >
            {children}
          </Box>
        }
      </body>
    </html>
  );
}
