import Drawer from "./components/Drawer/Drawer";
import { ThemeProvider } from "./context/theme-provider";
import { TranslationProvider } from "./context/TranslationContext";
import "./globals.css";
import { Cairo } from "next/font/google";
import Link from "next/link";
const cairo = Cairo({
  subsets: ["arabic"],
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cairo.className} antialiased min-h-screen`}>
        <TranslationProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="">
              <Drawer />
            </div>
            {children}
          </ThemeProvider>
        </TranslationProvider>
      </body>
    </html>
  );
}
